# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7baba4bc7c76b4bd0f058b3d67389aea491e3726aafc9fe7c2c019902245fcd0a3fda90b6778866c29c8dfbbfb3a3e488d8c3e7b35226e4e49c9765a1adf4da1

test:
  secret_key_base: 7c242bc946b75a362ce1468fda9d2aa5e8c7a6eb687eec1a8a6d8282dc33fe72aaef4d0b6049629d114b41d905f19ac8034e1c3738ea38ff043e6e9aa8f67b5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
